sources:
  - name: sample_postgres
    type: postgres
    host: localhost
    user: postgres
    password: Ranchi0651
    dbname: etl_source
    tables:
      - name: process_area
        joins: []
        filters: []

target:
  type: sqlserver
  host: localhost\SQLEXPRESS
  trusted_connection: yes 
  dbname: etl_target

threading:
  max_threads: 3
