sources:
  - name: sample_postgres
    type: postgres
    host: localhost
    port: 5432
    user: postgres
    password: Ranchi0651 
    dbname: etl_demo      
    tables:
      - name: process_area
        joins: []
        filters: []

target:
  type: sqlserver
  host: localhost\SQLEXPRESS
  dbname: etl_demo
  trusted_connection: yes   

threading:
  max_threads: 3
